import { IRecipe } from '../recipes/recipe';

export const RECIPESDATA: IRecipe[] = [{
  id: 1,
  name : "Gel-Fujitrabuco 5 G-Tx",
  type : "Running Shoe",
  description: "God og robust terrænløbesko med GORE- TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod....",
  longdescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  sizes : ["45", "44", "43"],
  image: "app/assets/img/shoe-item.jpg",
  imagetwo: "app/assets/img/shoe-big.jpg",
  imagethree: "app/assets/img/shoe-item.jpg",
  imagefour: "app/assets/img/shoe-item.jpg",
  brand: "app/assets/img/asics.jpg",
  stock : 80,
  price: 86,
  isfeatured: true,
  likes: 100
},{
  id: 2,
  name : "Gel-Fujitrabuco 5 G-Tx",
  type : "Running Shoe",
  description: "God og robust terrænløbesko med GORE- TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod....",
  longdescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  sizes : ["45", "44", "43"],
  image: "app/assets/img/shoe-item.jpg",
  imagetwo: "app/assets/img/shoe-big.jpg",
  imagethree: "app/assets/img/shoe-item.jpg",
  imagefour: "app/assets/img/shoe-item.jpg",
  brand: "app/assets/img/asics.jpg",
  stock : 80,
  price: 86,
  isfeatured: true,
  likes: 100
},
{
  id: 3,
  name : "Gel-Fujitrabuco 5 G-Tx",
  type : "Running Shoe",
  description: "God og robust terrænløbesko med GORE- TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod....",
  longdescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  sizes : ["45", "44", "43"],
  image: "app/assets/img/shoe-item.jpg",
  imagetwo: "app/assets/img/shoe-big.jpg",
  imagethree: "app/assets/img/shoe-item.jpg",
  imagefour: "app/assets/img/shoe-item.jpg",
  brand: "app/assets/img/asics.jpg",
  stock : 80,
  price: 86,
  isfeatured: true,
  likes: 100
},
{
  id: 4,
  name : "Gel-Fujitrabuco 5 G-Tx",
  type : "Running Shoe",
  description: "God og robust terrænløbesko med GORE- TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod....",
  longdescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  sizes : ["45", "44", "43"],
  image: "app/assets/img/shoe-item.jpg",
  imagetwo: "app/assets/img/shoe-big.jpg",
  imagethree: "app/assets/img/shoe-item.jpg",
  imagefour: "app/assets/img/shoe-item.jpg",
  brand: "app/assets/img/asics.jpg",
  stock : 80,
  price: 86,
  isfeatured: true,
  likes: 100
}
]
